name: Issue Template
description: Issue を立てる時に使います
title: "[Todo]: "
body:
  - type: textarea
    attributes:
      label: やること色々
      description: |
        - **AsIs**: 今の状況
        - **ToBe**: 理想の状況
        - **Action**: 具体的にやること
        - **Challenge**: 手をつけられたらやること
      value: |
        ## AsIs
        ## ToBe
        ## Action
        ## Challenge
    validations:
      required: true