name: Lint with ruff

on:
  pull_request:
    branches:
      - dev
      - main

jobs:
  python-linting:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12.1

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/poetry
          ~/.cache/pip
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: ${{ runner.os }}-poetry

    # Linter ruff の実行
    - uses: chartboost/ruff-action@v1
    - name: Run syntax check
      run: poetry run ruff --output-format=github .
      continue-on-error: true
