name: Python linting with ruff

on: [push, pull_request]

jobs:
  python-linting:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12.1

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/poetry
          ~/.cache/pip
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-poetry

    - uses: chartboost/ruff-action@v1
    - name: Run syntax check
      run: |
        ruff --output-format=github .
      continue-on-error: true
